ALTER TABLE member DROP COLUMN oid;
ALTER TABLE member DROP COLUMN ourl;

ALTER TABLE plan ADD COLUMN ori smallint NOT NULL DEFAULT 0;
ALTER TABLE plan ADD COLUMN oid varchar(256) NOT NULL DEFAULT '';
ALTER TABLE plan ADD COLUMN ourl varchar(256) NOT NULL DEFAULT '';
